# frozen_string_literal: true

source "https://rubygems.org"

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "selenium-webdriver", "= 3.10.0"
gem "appium_lib", "= 9.14.3"
gem 'parallel_split_test'

