# frozen_string_literal: true

require "rspec/core/rake_task"
ENV['BUILD_TIME'] = Time.now.strftime("%s")

RSpec::Core::RakeTask.new(:spec)

task default: :spec

desc 'Run all tests in parallel'
task :parallel do
  result = system 'parallel_split_test spec'
  raise StandardError, "Not everything passed" unless result
end
