# frozen_string_literal: true

source "https://rubygems.org"

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

# gem "appium_lib", "= 11.2.0"
gem "parallel_split_test"
gem "selenium-webdriver", "= 4.0.0.beta4"
