# frozen_string_literal: true

require "rspec/core/rake_task"
ENV['BUILD_TIME'] = Time.now.to_s

RSpec::Core::RakeTask.new(:spec)

task default: :spec

desc 'Run all tests in parallel'
task :parallel do
  result = system 'parallel_split_test spec'
  raise StandardError, 'Tests failed!' unless result
end

desc 'Run mobile tests in parallel'
task :mobile do
  result = system 'parallel_split_test spec/mobile_*_spec.rb'
  raise StandardError, 'Tests failed!' unless result
end
