name: .NET Tests

on:
  - push
  - pull_request

jobs:
  csharp-tests:
    name: C# Tests
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        dir: [ se3-legacy, se3last-w3c, se4-w3c ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        working-directory: dotnet/${{ matrix.dir }}
        run: |
          dotnet restore ${{ matrix.dir }}.csproj --verbosity detailed
      - name: Run ${{ matrix.dir }} tests
        working-directory: dotnet/${{ matrix.dir }}
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: dotnet/${{ matrix.dir }}
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: dotnet test --no-restore --verbosity normal
