name: Java Tests

on:
  - push
  - pull_request

jobs:
  java-tests:
    name: Java Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: [ se2-legacy, se3-legacy, se3-w3c, se3last-w3c, se4-w3c ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run testng tests
        working-directory: java/${{ matrix.dir }}
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: mvn test -X
