name: Ruby Tests

on:
  - push
  - pull_request

jobs:
  ruby-tests:
    name: Ruby Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: [ se3-legacy, se3-w3c, se3last-legacy, se3last-w3c, se4-w3c ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install Dependencies
        working-directory: ruby/${{ matrix.dir }}
        run: bundle install
      - name: Run ${{ matrix.dir }} tests
        working-directory: ruby/${{ matrix.dir }}
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          PARALLEL_SPLIT_TEST_PROCESSES: '20'
        run: bundle exec rake parallel
